services:
  api:
    container_name: madi-api-dev
    command: bun start 
    env_file: .env.development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "./:/app"
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - madi_network
  db:
    container_name: madi-db-dev
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - madi_network

volumes:
  madi_data:
networks:
  madi_network:
    driver: bridge
