services:
  api:
    container_name: api-dev
    command: bash -c "bun generate && bun start:dev"
    env_file: .env.development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "./:/app"
    ports:
      - "8000:8000"
